### ISSUE TITLE
No documentation for how to connect an Echo to this

### ISSUE THREAD

**Issue by monokrome** [alexa-js/alexa-app-server#10]
Is it possible to update the README with some documentation on how to connect your echo to it? Even if it's just a link to relevant docs, it'd be super helpful :)

**Comment by matthewkimber** [comment]
I am pretty sure this isn't meant to be used with a physical device. It is really just a local simulator. The following is from the readme file:

> "The server can also serve static web site content, and offers a built-in Alexa App debugger/simulator. This allows you to test your skill using a web browser and view the responses, *without actually using the Echo.*"

Hope this helps.

**Comment by willis7** [comment]
There is a tutorial series which uses this for the TDD, and the end result is a deployed skill.

[part 1](https://developer.amazon.com/public/community/post/Tx3DV6ANE5HTG9H/Big-Nerd-Ranch-Series-Developing-Alexa-Skills-Locally-with-Node-js-Setting-Up-Yo)

I hope this helps

**Comment by TomMettam** [comment]
I have a live skill in the Amazon store served by this. It's been possible since we added support for the amazon verifier.

**Comment by masterchop** [comment]
So do we need to setup a cert and start it as https and use that URL in alexa dev section?

**Comment by dblock** [comment]
+1 on documentation, PRs welcome

**Comment by monokrome** [comment]
Thanks for all the info on this. It's super helpful :) :)

**Comment by cpup22** [comment]
@TomMettam how'd you get your skill to pass verification?  We've got open issues with setting the verify flag to true causing the skill to timeout. se: #52 #50

**Comment by TomMettam** [comment]
@cpup22 : Unfortunately there has been a regression somewhere in this repo - the functionality is broken. However, I'm maintaining a working repo at https://github.com/CasperTech/alexa-app-server which has passed certification.

**Comment by dblock** [comment]
We're going to sort all this out, with tests so we don't reintroduce regressions. @TomMettam if you have time see comments on #52, and give more recent code a try.

**Comment by TomMettam** [comment]
dblock: I'm very sorry but at the moment I don't have time to write tests for this - i'm busy with work at the minute.

**Comment by dblock** [comment]
I've documented how to run alexa-app-server in production in https://github.com/alexa-js/alexa-app-server/pull/69, please make improvements/suggestions.

**Comment by monokrome** [comment]
:dancer:
