### ISSUE TITLE
Syntax generation for new Skill Builder interface

### ISSUE THREAD

**Issue by jradwan** [alexa-js/alexa-app-server#109]
Amazon is pushing the new Skills Builder UI for defining the interaction model. Would it be possible to have the skill's alexa-app-server endpoint generate the new code syntax in addition to the current schema and utterances outputs?

![image](https://user-images.githubusercontent.com/11047158/37185150-fcba093a-230c-11e8-9df2-2aee38df1e26.png)

![image](https://user-images.githubusercontent.com/11047158/37185191-2ea1ab10-230d-11e8-9978-ef513130c3f0.png)

**Comment by dblock** [comment]
Is this related to https://github.com/alexa-js/alexa-app/pull/268? Do we need to expose something in this library?

**Comment by jradwan** [comment]
@dblock that does seem to be what I'm referring too ... I didn't think to check alexa-app as I thought the schema was being generated by alexa-app-server. I'll check that out, thanks!
