### ISSUE TITLE
Is this repository still being actively maintained?

### ISSUE THREAD

**Issue by gfyoung** [alexa-js/alexa-app-server#112]
I noticed that the [last commit](https://github.com/alexa-js/alexa-app-server/commit/562d16722c581ddd9ba052355143489b5af31619) was made over a year ago.

**Comment by dblock** [comment]
Yes it is. It just has been working pretty well. Maybe make some PRs to refresh things? ;)

**Comment by gfyoung** [comment]
Is there a reason why `3.0.2` was never released into the wild?

**Comment by dblock** [comment]
No reason, https://github.com/alexa-js/alexa-app-server/issues/114.
