### ISSUE TITLE
Node 7.10.0 and 7.10.1 fail custom binding tests

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app-server#115]
Latest release (v3.0.2) is breaking on half of the node versions, specifically node v7 being the highest priority to fix.

**Comment by tejashah88** [comment]
@dblock

**Comment by dblock** [comment]
Uh oh, that's not good.

**Comment by tejashah88** [comment]
I made a PR (#117) to test if the later node versions are having a similar issue, and it seems that only node 7 has this problem.

**Comment by tejashah88** [comment]
Some more testing has led me to the following:
- The failing parts of the tests are with custom bindings to a specific host and port, specifically with a refused connection error
- Node versions 7.10.0 and 7.10.1 are the only versions breaking, as previous ones are working perfectly
- I've been unsuccessful with reproducing the same error on my PC, which is running windows 10 with node 7.10.1

Checking the change log from 7.9.0 to 7.10.0 didn't seem to offer any insight, and I'm not sure how I should proceed further, since this is such an isolated issue.

**Comment by dblock** [comment]
I would rename this issue into describing the problem on node 7 and remove it from the matrix in a PR and merge that.

**Comment by tejashah88** [comment]
That works for now. While we're on the subject, what should we do for node verions 1-3 on the matrix, since they are failing due to the use of arrow functions from the test libraries?
