### ISSUE TITLE
{"status":"failure","reason":"missing certificate url"}

### ISSUE THREAD

**Issue by getmohanraj95** [alexa-js/alexa-app-server#118]
Hello all,
i am facing this issue for production environment, even though i have used new certificate from a certified company. am having this issue.
ISSUE:

{"status":"failure","reason":"missing certificate url"}

Could any one help me to resolve this issue.

**Comment by tamerbak** [comment]
Hi @getmohanraj95 ,
I see that you closed this issue did you find a solution ?

**Comment by getmohanraj95** [comment]
@tamerbak yes, i found the solution and its going good.

Its all because of the ssl certificate path & merge the two certificates correctly.

**Comment by sajanthomas01** [comment]
@getmohanraj95 can you explain how you solved this, I'm facing exactly the same error

**Comment by getmohanraj95** [comment]
Issues is because of ssl.
Install ssl certification correctly in the server . You can resolve this.
