### ISSUE TITLE
Add I18n support

### ISSUE THREAD

**Issue by rotero** [alexa-js/alexa-app-server#12]
The request templates don't have the locale attribute need for i18n

**Comment by dblock** [comment]
Labeling this as new feature. PRs welcome.

**Comment by tejashah88** [comment]
This module ([i18n-node](https://github.com/mashpie/i18n-node)) might be a good place to start.

**Comment by siedi** [comment]
The i18n implementation should belong to alexa-app see [issue #117](https://github.com/alexa-js/alexa-app/issues/127)

**Comment by dblock** [comment]
The simulator selector was added in https://github.com/alexa-js/alexa-app-server/pull/74.
