### ISSUE TITLE
Support for ca chain certificates

### ISSUE THREAD

**Issue by CarbonCollins** [alexa-js/alexa-app-server#17]
Hello, 

Alexa would not connect to the server with the SSL cert that I had without also including the ca bundle (spent several hours of it working on my local machine and not on Alexa dev network to figure this one out)

I have forked and have added the code [here](https://github.com/divergentlepton/alexa-app-server) and have made the ca cert optional as to keep the original functionality and to allow the inclusion of the cert if available.

**Comment by dblock** [comment]
@CarbonCollins You should PR your changes please, see https://github.com/alexa-js/alexa-app-server/blob/master/CONTRIBUTING.md

**Comment by tejashah88** [comment]
Resolved with #45. Closing...
