### ISSUE TITLE
req.slot should not log console error when default value is passed

### ISSUE THREAD

**Issue by thehungrycoder** [alexa-js/alexa-app-server#20]
```req.slot('abc', null)```
If `abc` isn't passed with intent request, it'll report error like
```
missing intent in request: abc [TypeError: Cannot read property 'value' of undefined]
```

IMO, passing default value means it can be empty and consumer of this method will handle it. In this case we shouldn't log as error. At most, we can set as warning. 

I can send a PR if you agree.

**Comment by dblock** [comment]
Sounds reasonable, please PR.

**Comment by tejashah88** [comment]
This issue is better suited for [alexa-app](https://github.com/alexa-js/alexa-app). You might also want to look at this [line](https://github.com/alexa-js/alexa-app/blob/master/index.js#L176) that's causing the "error" persay.
