### ISSUE TITLE
Request hangs during POST with body content

### ISSUE THREAD

**Issue by dale3h** [alexa-js/alexa-app-server#21]
I have a script in the `server` directory that requires POST method, and it hangs now that I've updated alexa-app-server. I was able to get around this by wrapping the raw body function with:

```
if (config.verify) {
  ...raw body parser for request verification...
}
```

It seems like `req.on('data', function(data) {` does not get called if the POST method is used.

**Comment by dale3h** [comment]
Actually, doing that broke the server. This seems to work in place of the current rawBody parser:

```
//We need the rawBody for request verification
self.express.use(bodyParser.json({
	verify: function(req, res, buf, encoding) {
		req.rawBody = buf.toString();
	}
}));
```

**Comment by dblock** [comment]
@dale3h did you dig this up? What should we do with this?

**Comment by rickwargo** [comment]
@dale3h I think I may have had the same issue. While I haven't fixed it, a patch made it work for me. See details at https://github.com/alexa-js/alexa-app/pull/144#issuecomment-276729326
