### ISSUE TITLE
Invalid schema for guessinggame example.

### ISSUE THREAD

**Issue by seattleacademy** [alexa-js/alexa-app-server#39]
When attempting to add intents and utterances to the Amazon app portal for the example app guessing game, an error message is displayed:

_Error: There was a problem with your request: 'guess' is an intent name as well as a slot name. Slot names and intent names must not overlap.__

**Comment by dblock** [comment]
where's this guessing game example?

**Comment by seattleacademy** [comment]
@dblock:  Here is the example.  Changing line 16 from **game** to **GameIntent** would seem to be the best solution.
https://github.com/alexa-js/alexa-app-server/tree/master/examples/apps/number_guessing_game

**Comment by dblock** [comment]
Oh I see. If you could debug the examples and fix them in a PR that would be great. Ideally we also want automated tests against them. Thx.

**Comment by tejashah88** [comment]
Looks like this has been fixed in #40. Closing.
