### ISSUE TITLE
Re-organize tests

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app-server#41]
The current tests are not organized properly. If anyone is willing to re-write the tests, please send a PR.

**Comment by mreinstein** [comment]
> The current tests are not organized properly

This is too vague for me to weight in on. I don't konw what properly means.

**Comment by tejashah88** [comment]
Actually, it's really not needed as #57 is more descriptive of what changes the tests need. When I originally made this issue, it seemed to me at the time that some parts are redundantly tested where-as other parts were not tested enough.

Closing in favor of #57...
