### ISSUE TITLE
Templates in test.ejs do not include context property.  userId is extracted from this...

### ISSUE THREAD

**Issue by bwmcin** [alexa-js/alexa-app-server#42]
I am learning the Alexa ecosystem and in running the persistence tutorial, the execution failed due to userId being null.  It appears the alexa-app is pulling the userId from the context property, but the request template does not have said property.  I modified my copy of test.ejs and it now works.  Is there another configuration parameter that I should have set so that his would happen "automagically"?

**Comment by dblock** [comment]
What's this persistence tutorial? :)

**Comment by tejashah88** [comment]
I believe this is because #22 was not merged yet.

**Comment by dblock** [comment]
Aha. Could we finish #22 with some tests pls?

**Comment by bwmcin** [comment]
Yes, it was. And I was also playing with the chip tutorial.  I believe the persistence tutorial also has another error in the refactoring—I will had to do some more exploring on that.

 

Regards,

 

Bruce

**Comment by tejashah88** [comment]
@dblock By tests, you mean for mocha or actually testing it, since i didn't necessarily find any mocha tests for this?

**Comment by dblock** [comment]
Yes. We're changing some code, we want tests that otherwise would break. New management new rules, no more untested code ;)

**Comment by tejashah88** [comment]
I understand that we need testing, but any specifics for how to do so? (ie. mocha testing or manually testing?)

**Comment by dblock** [comment]
Mocha of course.

**Comment by tejashah88** [comment]
After trying for a couple of days, there doesn't seem to be an easy solution to test this without some breaking changes to the debugger. IMO, if the alexa-app and alexa-app-server core code are tested well enough, there shouldn't need to be testing the debugger, at least with mocha. Currently, I'm re-factoring the [test.ejs](https://github.com/alexa-js/alexa-app-server/blob/master/views/test.ejs) file, as it's pretty much a big mess to maintain right now. Until we have a way of testing the debugger otherwise, I'd say we leave it alone otherwise.

**Comment by dblock** [comment]
I only disagree "in principle", any code we ship that users can use should have automated tests because otherwise we break it every time we make a change or new contributors are scared of contributing.

**Comment by bwmcin** [comment]
Just for context, I was "following" the directions on the tutorial and found that the persistence didn't work.  In debugging the problem, I discovered that the template for the intents was in test.ejs.   I would suggest that since the tutorial "requires" this file, that in one sense, this isn't a "test" file, nor is it a "debugging" file.  Did I miss the instructions somewhere that one needs to modify this file before using the persistence mechanism?  I would believe you test scenario should process all intents that are to be experienced by the folks learning the system.  Thank you.

**Comment by dblock** [comment]
I merged #22, we can pay our technical debts later.
