### ISSUE TITLE
Add support for more node versions for Travis-CI

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app-server#49]
Currently, the only tested node versions are v6 and v7 (according to [travis-ci](https://travis-ci.org/alexa-js/alexa-app-server/builds/196866002)). It's not very easy to add other versions without some errors encountered, mainly with [danger-js](https://github.com/danger/danger-js) (see #48 for attempts by me to solve this issue).

If future releases of alexa-app-server are to intentionally drop support for older versions of node, it's best to add a section in the README stating which versions **are** supported.

**Comment by dblock** [comment]
+1 on adding a section for which versions of node are supported
