### ISSUE TITLE
Add Listen IP config option

### ISSUE THREAD

**Issue by arch1v1st** [alexa-js/alexa-app-server#5]
Hi,

Would you please add a 'listen' IP configuration option to AlexaAppServer.start()?  For example, in index.js, line 218, add a config.listen variable...

self.express.listen(config.port, config.listen);

This way, users can control the listen IP address for the service.  For now we are 'hacking' it by modifying this line to:

self.express.listen(config.port, '149.2.28.245');

Thanks!

**Comment by spyglobalsolutions** [comment]
Hi I have no idea what you wanted the person to do but I'm really interested in finding out would you please explain

**Comment by dblock** [comment]
This is a good idea, [PRs welcome](https://github.com/alexa-js/alexa-app-server/blob/master/CONTRIBUTING.md).

**Comment by tejashah88** [comment]
Closed via #37.
