### ISSUE TITLE
isPortTaken tests don't work

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app-server#53]
I put garbage instead of port numbers in the tests that call `isPortTaken` and they still pass. Something looks not right, this should return a promise and reject it?

**Comment by tejashah88** [comment]
@dblock Could you elaborate on the "garbage" that you put for `isPortTaken`?

**Comment by dblock** [comment]
Change the port anywhere in tests where you call `isPortTaken` from 3000 to 1234 and all tests still pass.

**Comment by dblock** [comment]
Closing this since https://github.com/alexa-js/alexa-app-server/pull/60 doesn't reintroduce this bug.
