### ISSUE TITLE
Deal with multiple slashes in normalizedRoot

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app-server#68]
From https://github.com/alexa-js/alexa-app-server/pull/64

> One (simple) formatting suggestion is to remove trailing slashes from the normalizedRoot in self.loadapps(). The comments have an example where the server root ends with a slash and if included, the message says, "loaded app [hello_world] at endpoint: /alexa//hello_world."

**Comment by dblock** [comment]
The better way to handle it is also to use some path combine function/library that deals with any number of slashes or relative paths.

**Comment by tejashah88** [comment]
A simple regex replace operation would work as well. I can make a PR for that.

**Comment by dblock** [comment]
There be dragons. Unicode path names, etcetera. Use node.js `Path.join`, http://softwareengineering.stackexchange.com/questions/267846/is-there-a-conventional-way-to-combine-file-path-strings.

**Comment by tejashah88** [comment]
You could also use `Path.normalize` as well, https://nodejs.org/api/path.html#path_path_normalize_path

**Comment by dblock** [comment]
If you hurry it might make it into this release :)

**Comment by tejashah88** [comment]
Should be solved with #71

**Comment by mreinstein** [comment]
> If you hurry

no, please do not. :(
