### ISSUE TITLE
How can i make a http request?

### ISSUE THREAD

**Issue by NullP0interEx** [alexa-js/alexa-app-server#75]
Can you please add an example skill with a http request? 
I want to query an API but i think my way is not so perfect.

`var alexa = require('alexa-app');
var async = require('async');
var request = require('request');

// Allow this module to be reloaded by hotswap when changed
module.change_code = 1;

// Define an alexa-app
var app = new alexa.app('hello_world');

async.parallel([
      function(callback) {
        var options = {
        url:  'https://xxxxxxxxxx.de/ddd',
        timeout: 3000
      }
      request(options, function(err, response, body) {
        // JSON body
        if(err) { console.log(err); callback(true); return; }
        obj = JSON.parse(body);
        callback(false, obj);
      });
    }],
    function(err, results) {
      app.launch(function(req, res) {
            sayToday(results[0], req, res);
      });

      app.intent('DayIntent', {
        "slots": { "DAY": "DAY_OF_WEEK"},
        "utterances": ["xxxxx"]
      }, function(req, res) {
          if(err) { 
            res.say("sdfsdfsdfsdf"); 
            return; 
          }
          
          //parse JSON
      });
      
    }
  );`

**Comment by dblock** [comment]
There're a thousand ways to do this, here's one with [request-promise](https://www.npmjs.com/package/request-promise).

```js
app.intent('ReposIntent', {}, function(req, res) {

  var options = {
    uri: 'https://api.github.com/user/repos',
    qs: {
        access_token: 'xxxxx xxxxx'
    },
    json: true
  };
 
  return rp(options)
    .then(function (repos) {
        res.say('User has ' + repos.length + ' repos.');
    });
});
```
