### ISSUE TITLE
Application ID not getting set when testing(debug)

### ISSUE THREAD

**Issue by nedhanks** [alexa-js/alexa-app-server#77]
I have added the application id to the project.json file. I verified that app.id is getting set by adding a console.log into node_modules/alexa-app-server/index.js(line 112).

But when I bring up the POST testing page the application id is not being replaced in the template.  I'm don't do much browser javascript programming, and can't figure out why.  

Is this a bug, or did I miss a configuration step somewhere?

**Comment by dblock** [comment]
It's probably a bug.

**Comment by dblock** [comment]
Fixed via https://github.com/alexa-js/alexa-app-server/commit/6924e903e205bf26d795b3a0d7d8021aa6a41b76.
