### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by tlovett1** [alexa-js/alexa-app-server#80]
Hey guys, just wanted to let you know I built a similar app server for the [Amazon SDK for Node.js](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) inspired by this project:

https://github.com/tlovett1/alexa-skill-test

**Comment by dblock** [comment]
Thanks. If you are interested in having that part of the alexa-js org, we'd be happy to have you - transfer it to me and I'll transfer it into the org right away. Of course you keep doing what you're doing.
