### ISSUE TITLE
how to configure on the Amazon side?

### ISSUE THREAD

**Issue by ericblade** [alexa-js/alexa-app-server#81]
question:

I've put together an alexa-app-server, with https support as described in the README, but no amount of fooling with the settings on developer.amazon.com seems to get it to work.  I just get "The SSL handshake failed".  I also tried following the Amazon directions for generating a certificate, and put it in the same place in the alexa-app-server and get the same response.

Any ideas or suggestions?  I know it's not directly related to the app-server, but I'm hoping someone might have some experience they can lend.

**Comment by ericblade** [comment]
Figured it out -- must have a valid DNS name and have it applied to the certificate.

**Comment by dblock** [comment]
Maybe you want to document this for the rest of us? PR?
