### ISSUE TITLE
Express on Lambda as a proxy between Alexa and localhost alexa-app-server

### ISSUE THREAD

**Issue by benedekh** [alexa-js/alexa-app-server#89]
It is a rather off-topic question, but is it possible to [deploy an Express server on Lambda](https://claudiajs.com/tutorials/serverless-express.html) that forwards the requests from Alexa to my webserver? Basically I just would like to use Lambda as a proxy between my computer (that has an alexa-app-server running but without HTTPS) and Amazon Voice Service.

**Comment by dblock** [comment]
Express runs 24/7 so I don't think it can work on Lambda as that is per request AFAIK.

**Comment by benedekh** [comment]
What I meant was, I can deploy a website on Lambda using aws-serverless-express and that would forward the request to my skill. My question was, if it is possible or due to some limitations by AWS / Alexa not.

**Comment by dblock** [comment]
Oh I've never used aws-serverless-express, it wasn't clear that you're trying to use that. I would say there's no reason why `alexa-app` wouldn't work with that, however `alexa-app-server` has a dependency on `express` proper. It's possible that it "just works" against aws-serverless-express, and if it does we should maybe figure out how to make the express part swappable here. PRs welcome.

**Comment by muneerkk66** [comment]
I have successfully link the user in my own system. The access token which i'am getting from lambda function and the token which i got from after user authorisation is different. Do you have any idea about this.
