### ISSUE TITLE
Add request signature verification

### ISSUE THREAD

**Issue by martijnthe** [alexa-js/alexa-app-server#9]
Maybe I missed it, but this seems to be missing from this library?

See this page for the requirements:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#Verifying%20that%20the%20Request%20was%20Sent%20by%20Alexa

**Comment by jradwan** [comment]
I'd like to see this too. I've been trying to figure out how to use (alexa-verifier)[https://github.com/mreinstein/alexa-verifier] with alexa-app-server and without Express and have not been successful. Incorporating this into alexa-app-server would be a nice addition.

**Comment by bluepuma77** [comment]
+1

**Comment by TomMettam** [comment]
https://github.com/matt-kruse/alexa-app-server/pull/14

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app-server/pull/14.
