### ISSUE TITLE
Play an Audio Stream?

### ISSUE THREAD

**Issue by mclucario** [alexa-js/alexa-app-server#93]
Is it possible to play an online audio stream/file with this server on Alexa? I haven't found anything in the examples or package to use it with. It would be nice to have an example or a small documentation for stuff like this.

My PHPStorm gave me `res.play();` but that didn't really work out either.

**Comment by dblock** [comment]
Yes. See https://github.com/alexa-js/alexa-app, `response.audioPlayerPlayStream`. Example: https://github.com/artsy/elderfield/blob/master/functions/artsy/index.js#L298

**Comment by mclucario** [comment]
Oh, I see now how it is.
