### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by JohnStraumann** [alexa-js/alexa-app-server#99]
Hi all:

I downloaded on Windows, and extracted the ZIP file to "Downloads\alexa-app-server-master", and ran:

npm install 

Which seemed to work, but then when I tried to run:

node server

I get an error: "Error: Cannot find module 'D:\Data\Amazon\alexa-app-server\examples\server\server"

There is a "server" folder in the "examples director"...

Note I am a TOTAL noob, working through the book "Building Voice-Enabled Apps with Alexa"...

Any and all advice is greatly appreciated.

John.

**Comment by dblock** [comment]
This is a library that you can use, but not "download & install". Maybe go through http://code.dblock.org/2017/02/16/building-a-simple-alexa-skill-live-code.html first?

Closing this but feel free to ask more questions.

**Comment by JohnStraumann** [comment]
Thanks for your response, but if this is not "installable", why does the readme.md say this:


## Installation

```
npm install alexa-app-server --save

**Comment by dblock** [comment]
You can do that, but you don't need to download anything, it gets that from npmjs.org.
